### PR TITLE
First pass at CLI + Universal, build works

### PR DESCRIPTION
**Pull request by mrjmd**
Work in progress, but the ssr build works!

### CODE REVIEW

**Comment by mrjmd** [comment]
Current status:

- Check out branch
- `npm install`
- `ng build --prod --app universal`
- `node index.js`

Then you'll see the issues our app currently has with universal.

**Review by joaogarin — COMMENTED** [review]
Yay! this is great :tada: :balloon: 

I think I would like to have a app.browser.module sit on top of the AppModule like with the app.server.module is now.

The reason is that it will make a lot simpler to leverage DI when using things that are client specific. So if for example you have something that uses websockets, or a service that uses memory on the server and localstorage on the client, these can be abstracted nicely and injected in each of the modules accordingly.

The implementation is like what is seen on https://github.com/FrozenPandaz/ng-universal-demo/tree/master/src/app

**Comment by mrjmd** [comment]
Good call @joaogarin. The latest commit moves us in this direction, with app.browser.module and app.server.module that both import the common app.module.

I moved the hammerjs import into browser only and that moved us a small step forward. I guess we'll have to go through and figure out which pieces give Universal problems.

The main app still works fine, and the ssr one builds fine but has runtime issues from node. In theory we could even merge and iterate on this since it doesn't break our live app, but better to fix it here first I think.

**Comment by mrjmd** [comment]
This is working pretty nicely on my local now. Here's how I'm running it currently:

- `ng build --prod`
- `ng build --prod --app universal --output-hashing none`
- `node index.js`
- `serve -s dist-client/`

^ Note that you must have the `serve` package installed globally for that last command. Then you can navigate to localhost:5000 and view source, and you will see a server rendered app with handoff to client!

So, Universal 'works', but I'm not sure whether we should merge it as is for now or not. What is actually getting rendered at this point is very minimal and will need to be investigated and improved. Then we need to put effort into optimizing things to move as much of our initial work to server-only as possible (there's no good reason our initial API calls should happen on the client, but right now they do).

And anyway, until we get Cloud Functions set up, our Firebase site still won't use this setup.

But I guess all of those could be follow up tasks. Thoughts @joaogarin? Maybe we could merge this, then I'll work on the cloud function while you look into why so little is getting rendered server side right now?

**Pull request closed without merging**
